
title:
  en: Gladys Assistant Documentation
  fr: Gladys Assistant Documentation

description:
  en: Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  fr: Écrivez une super description de votre nouveau site ici. Vous pouvez modifier cette ligne dans _config.yml. Elle apparaîtra dans la balise meta description (pour les résultats sur Google) et dans le fil RSS feed.xml.

collections:
  docs:
    output: true
    permalink: /:path

# Social network
twitter_username: gladysassistant
github_username:  gladysassistant
facebook_username: gladysassistant
instagram_username: gladysassistant

## I18N
languages: ["en", "fr"]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: en
languageNames:
  fr: Français
  en: English

#SEO plugins infos
twitter:
  username: gladysassistant
logo: /assets/image/gladys-logo.png
social:
  name: Gladys Assistant
  links:
    - https://twitter.com/gladysassistant
    - https://www.facebook.com/gladysassistant
    - https://www.instagram.com/gladysassistant
    - https://github.com/gladysassistant

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
